# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Docbot

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build Javadocs
      run: ./gradlew javadoc
    - name: Push Javadocs
      run: |
        mkdir docs-src && git clone https://github.com/tmthecoder/docs docs-src
        cd docs-src
        echo "docs.tmthecoder.dev" > CNAME
        git config user.name  "Docbot"
        git config user.email "docbot@github.com"
        if [ -d OdometryCore/ ]; then rm -Rf OdometryCore/; fi
        cp -R ../build/docs/javadoc/ OdometryCore/
        git remote add secure-origin https://${{ secrets.ACCESS_TOKEN }}@github.com/tmthecoder/docs
        git add .
        git commit -m "Updated documentation for OdometryCore" --allow-empty
        git push secure-origin main

